// 中文字編碼資料
// 包含常用中文字的注音、倉頡、無蝦米、拼音編碼

const encodingData = {
    // 常用字 - 第一批
    '的': { zhuyin: 'ㄉㄜ˙', cangjie: '竹日弓', boshiamy: 'OI', pinyin: 'de' },
    '一': { zhuyin: 'ㄧ', cangjie: '一', boshiamy: 'N', pinyin: 'yī' },
    '是': { zhuyin: 'ㄕˋ', cangjie: '日一卜人', boshiamy: 'DAM', pinyin: 'shì' },
    '不': { zhuyin: 'ㄅㄨˋ', cangjie: '一火', boshiamy: 'MI', pinyin: 'bù' },
    '了': { zhuyin: 'ㄌㄜ˙', cangjie: '弓弓', boshiamy: 'L', pinyin: 'le' },
    '在': { zhuyin: 'ㄗㄞˋ', cangjie: '大土', boshiamy: 'KG', pinyin: 'zài' },
    '人': { zhuyin: 'ㄖㄣˊ', cangjie: '人', boshiamy: 'O', pinyin: 'rén' },
    '有': { zhuyin: 'ㄧㄡˇ', cangjie: '大月', boshiamy: 'KB', pinyin: 'yǒu' },
    '我': { zhuyin: 'ㄨㄛˇ', cangjie: '竹手戈', boshiamy: 'X', pinyin: 'wǒ' },
    '他': { zhuyin: 'ㄊㄚ', cangjie: '人心', boshiamy: 'OD', pinyin: 'tā' },
    '這': { zhuyin: 'ㄓㄜˋ', cangjie: '卜口大弓', boshiamy: 'YGS', pinyin: 'zhè' },
    '個': { zhuyin: 'ㄍㄜˋ', cangjie: '人口竹口', boshiamy: 'ORR', pinyin: 'gè' },
    '們': { zhuyin: 'ㄇㄣ˙', cangjie: '人日弓', boshiamy: 'OAN', pinyin: 'men' },
    '中': { zhuyin: 'ㄓㄨㄥ', cangjie: '中', boshiamy: 'L', pinyin: 'zhōng' },
    '來': { zhuyin: 'ㄌㄞˊ', cangjie: '大木', boshiamy: 'KD', pinyin: 'lái' },
    '上': { zhuyin: 'ㄕㄤˋ', cangjie: '卜一', boshiamy: 'YM', pinyin: 'shàng' },
    '大': { zhuyin: 'ㄉㄚˋ', cangjie: '大', boshiamy: 'K', pinyin: 'dà' },
    '為': { zhuyin: 'ㄨㄟˋ', cangjie: '戈大弓火', boshiamy: 'IKF', pinyin: 'wèi' },
    '和': { zhuyin: 'ㄏㄜˊ', cangjie: '竹木口', boshiamy: 'HDR', pinyin: 'hé' },
    '國': { zhuyin: 'ㄍㄨㄛˊ', cangjie: '田戈口一', boshiamy: 'WIRM', pinyin: 'guó' },
    '地': { zhuyin: 'ㄉㄧˋ', cangjie: '土心木', boshiamy: 'GDP', pinyin: 'dì' },
    '到': { zhuyin: 'ㄉㄠˋ', cangjie: '一土中弓', boshiamy: 'MGLK', pinyin: 'dào' },
    '以': { zhuyin: 'ㄧˇ', cangjie: '女戈人', boshiamy: 'VIO', pinyin: 'yǐ' },
    '說': { zhuyin: 'ㄕㄨㄛ', cangjie: '卜口金口', boshiamy: 'YRCR', pinyin: 'shuō' },
    '時': { zhuyin: 'ㄕˊ', cangjie: '日土戈', boshiamy: 'AGI', pinyin: 'shí' },
    '要': { zhuyin: 'ㄧㄠˋ', cangjie: '一女火', boshiamy: 'MVF', pinyin: 'yào' },
    '就': { zhuyin: 'ㄐㄧㄡˋ', cangjie: '卜火大', boshiamy: 'YFK', pinyin: 'jiù' },
    '出': { zhuyin: 'ㄔㄨ', cangjie: '山山', boshiamy: 'UU', pinyin: 'chū' },
    '會': { zhuyin: 'ㄏㄨㄟˋ', cangjie: '人一日火', boshiamy: 'OMAF', pinyin: 'huì' },
    '可': { zhuyin: 'ㄎㄜˇ', cangjie: '一弓口', boshiamy: 'MNR', pinyin: 'kě' },
    '也': { zhuyin: 'ㄧㄝˇ', cangjie: '心木', boshiamy: 'PD', pinyin: 'yě' },
    '你': { zhuyin: 'ㄋㄧˇ', cangjie: '人弓火', boshiamy: 'ONF', pinyin: 'nǐ' },
    '對': { zhuyin: 'ㄉㄨㄟˋ', cangjie: '土口木戈', boshiamy: 'GRDI', pinyin: 'duì' },
    '生': { zhuyin: 'ㄕㄥ', cangjie: '竹手一', boshiamy: 'HQM', pinyin: 'shēng' },
    '能': { zhuyin: 'ㄋㄥˊ', cangjie: '戈月心心', boshiamy: 'IBPP', pinyin: 'néng' },
    '而': { zhuyin: 'ㄦˊ', cangjie: '一月中中', boshiamy: 'MBLL', pinyin: 'ér' },
    '子': { zhuyin: 'ㄗˇ', cangjie: '弓木', boshiamy: 'ND', pinyin: 'zǐ' },
    '那': { zhuyin: 'ㄋㄚˋ', cangjie: '弓木中', boshiamy: 'VL', pinyin: 'nà' },
    '得': { zhuyin: 'ㄉㄜˊ', cangjie: '竹人日一', boshiamy: 'HOAM', pinyin: 'dé' },
    '於': { zhuyin: 'ㄩˊ', cangjie: '卜大人', boshiamy: 'YKO', pinyin: 'yú' },
    '著': { zhuyin: 'ㄓㄜ˙', cangjie: '廿日十', boshiamy: 'TAJ', pinyin: 'zhe' },
    '下': { zhuyin: 'ㄒㄧㄚˋ', cangjie: '一卜', boshiamy: 'MY', pinyin: 'xià' },
    '自': { zhuyin: 'ㄗˋ', cangjie: '竹日山', boshiamy: 'HAU', pinyin: 'zì' },
    '之': { zhuyin: 'ㄓ', cangjie: '戈弓人', boshiamy: 'C', pinyin: 'zhī' },
    '年': { zhuyin: 'ㄋㄧㄢˊ', cangjie: '人手', boshiamy: 'OQ', pinyin: 'nián' },
    '過': { zhuyin: 'ㄍㄨㄛˋ', cangjie: '卜口月口', boshiamy: 'YRBR', pinyin: 'guò' },
    '發': { zhuyin: 'ㄈㄚ', cangjie: '弓人弓人水', boshiamy: 'NONE', pinyin: 'fā' },
    '後': { zhuyin: 'ㄏㄡˋ', cangjie: '竹人戈女大', boshiamy: 'HOIVK', pinyin: 'hòu' },
    '作': { zhuyin: 'ㄗㄨㄛˋ', cangjie: '人竹十', boshiamy: 'OHJ', pinyin: 'zuò' },
    '裡': { zhuyin: 'ㄌㄧˇ', cangjie: '中田土', boshiamy: 'LWG', pinyin: 'lǐ' },
    '用': { zhuyin: 'ㄩㄥˋ', cangjie: '月手', boshiamy: 'BQ', pinyin: 'yòng' },
    '道': { zhuyin: 'ㄉㄠˋ', cangjie: '卜廿竹山', boshiamy: 'YTHU', pinyin: 'dào' },
    '行': { zhuyin: 'ㄒㄧㄥˊ', cangjie: '竹人一一弓', boshiamy: 'HOMMN', pinyin: 'xíng' },
    '所': { zhuyin: 'ㄙㄨㄛˇ', cangjie: '竹尸竹中', boshiamy: 'HSHL', pinyin: 'suǒ' },
    '然': { zhuyin: 'ㄖㄢˊ', cangjie: '月大火', boshiamy: 'BKF', pinyin: 'rán' },
    '家': { zhuyin: 'ㄐㄧㄚ', cangjie: '十一尸人', boshiamy: 'JMSO', pinyin: 'jiā' },
    '種': { zhuyin: 'ㄓㄨㄥˇ', cangjie: '竹木竹十山', boshiamy: 'HDHJM', pinyin: 'zhǒng' },
    '事': { zhuyin: 'ㄕˋ', cangjie: '十中中弓', boshiamy: 'JLLN', pinyin: 'shì' },
    '成': { zhuyin: 'ㄔㄥˊ', cangjie: '戈竹尸', boshiamy: 'IHS', pinyin: 'chéng' },
    '方': { zhuyin: 'ㄈㄤ', cangjie: '卜竹尸', boshiamy: 'YHS', pinyin: 'fāng' },
    '多': { zhuyin: 'ㄉㄨㄛ', cangjie: '弓戈弓戈', boshiamy: 'NINI', pinyin: 'duō' },
    '經': { zhuyin: 'ㄐㄧㄥ', cangjie: '女火一女一', boshiamy: 'VFMVM', pinyin: 'jīng' },
    '麼': { zhuyin: 'ㄇㄜ˙', cangjie: '戈金竹', boshiamy: 'ICH', pinyin: 'me' },
    '去': { zhuyin: 'ㄑㄩˋ', cangjie: '土戈', boshiamy: 'GI', pinyin: 'qù' },
    '法': { zhuyin: 'ㄈㄚˇ', cangjie: '水戈土', boshiamy: 'EIG', pinyin: 'fǎ' },
    '學': { zhuyin: 'ㄒㄩㄝˊ', cangjie: '竹月弓木', boshiamy: 'HBND', pinyin: 'xué' },
    '如': { zhuyin: 'ㄖㄨˊ', cangjie: '女口', boshiamy: 'VR', pinyin: 'rú' },
    '都': { zhuyin: 'ㄉㄡ', cangjie: '十日弓中', boshiamy: 'JANL', pinyin: 'dōu' },
    '同': { zhuyin: 'ㄊㄨㄥˊ', cangjie: '月一口', boshiamy: 'BMR', pinyin: 'tóng' },
    '現': { zhuyin: 'ㄒㄧㄢˋ', cangjie: '一土月山山', boshiamy: 'MGBUU', pinyin: 'xiàn' },
    '當': { zhuyin: 'ㄉㄤ', cangjie: '火月口田', boshiamy: 'FBRW', pinyin: 'dāng' },
    '沒': { zhuyin: 'ㄇㄟˊ', cangjie: '水竹弓水', boshiamy: 'EHNE', pinyin: 'méi' },
    '動': { zhuyin: 'ㄉㄨㄥˋ', cangjie: '竹田大尸', boshiamy: 'HWKS', pinyin: 'dòng' },
    '面': { zhuyin: 'ㄇㄧㄢˋ', cangjie: '一田中中', boshiamy: 'MWLL', pinyin: 'miàn' },
    '起': { zhuyin: 'ㄑㄧˇ', cangjie: '走戈尸', boshiamy: 'GIS', pinyin: 'qǐ' },
    '看': { zhuyin: 'ㄎㄢˋ', cangjie: '竹手月山', boshiamy: 'HQBU', pinyin: 'kàn' },
    '定': { zhuyin: 'ㄉㄧㄥˋ', cangjie: '十一卜一', boshiamy: 'JMYM', pinyin: 'dìng' },
    '天': { zhuyin: 'ㄊㄧㄢ', cangjie: '一大', boshiamy: 'MK', pinyin: 'tiān' },
    '分': { zhuyin: 'ㄈㄣ', cangjie: '金尸竹', boshiamy: 'CSH', pinyin: 'fēn' },
    '還': { zhuyin: 'ㄏㄞˊ', cangjie: '卜田田月', boshiamy: 'YWWB', pinyin: 'hái' },
    '進': { zhuyin: 'ㄐㄧㄣˋ', cangjie: '卜竹人土', boshiamy: 'YHOG', pinyin: 'jìn' },
    '好': { zhuyin: 'ㄏㄠˇ', cangjie: '女弓木', boshiamy: 'VND', pinyin: 'hǎo' },
    '小': { zhuyin: 'ㄒㄧㄠˇ', cangjie: '弓金', boshiamy: 'NC', pinyin: 'xiǎo' },
    '部': { zhuyin: 'ㄅㄨˋ', cangjie: '卜口弓中', boshiamy: 'YRNL', pinyin: 'bù' },
    '其': { zhuyin: 'ㄑㄧˊ', cangjie: '廿一金', boshiamy: 'TMC', pinyin: 'qí' },
    '些': { zhuyin: 'ㄒㄧㄝ', cangjie: '卜一心', boshiamy: 'YMP', pinyin: 'xiē' },
    '主': { zhuyin: 'ㄓㄨˇ', cangjie: '卜土', boshiamy: 'YG', pinyin: 'zhǔ' },
    '樣': { zhuyin: 'ㄧㄤˋ', cangjie: '木廿土水', boshiamy: 'DTGE', pinyin: 'yàng' },
    '理': { zhuyin: 'ㄌㄧˇ', cangjie: '一土田土', boshiamy: 'MGWG', pinyin: 'lǐ' },
    '心': { zhuyin: 'ㄒㄧㄣ', cangjie: '心', boshiamy: 'P', pinyin: 'xīn' },
    '她': { zhuyin: 'ㄊㄚ', cangjie: '女心', boshiamy: 'VP', pinyin: 'tā' },
    '本': { zhuyin: 'ㄅㄣˇ', cangjie: '木一', boshiamy: 'DM', pinyin: 'běn' },
    '前': { zhuyin: 'ㄑㄧㄢˊ', cangjie: '竹口月中弓', boshiamy: 'HRBLN', pinyin: 'qián' },
    '開': { zhuyin: 'ㄎㄞ', cangjie: '日弓廿', boshiamy: 'ANT', pinyin: 'kāi' },
    '但': { zhuyin: 'ㄉㄢˋ', cangjie: '人日一', boshiamy: 'OAM', pinyin: 'dàn' },
    '因': { zhuyin: 'ㄧㄣ', cangjie: '田大', boshiamy: 'WK', pinyin: 'yīn' },
    '只': { zhuyin: 'ㄓˇ', cangjie: '口心', boshiamy: 'RP', pinyin: 'zhǐ' },
    '從': { zhuyin: 'ㄘㄨㄥˊ', cangjie: '竹人人人', boshiamy: 'HOOO', pinyin: 'cóng' },
    '想': { zhuyin: 'ㄒㄧㄤˇ', cangjie: '木月心', boshiamy: 'DBP', pinyin: 'xiǎng' },
    '實': { zhuyin: 'ㄕˊ', cangjie: '十月山金', boshiamy: 'JBUC', pinyin: 'shí' },

    // 練習文章中可能用到的字
    '打': { zhuyin: 'ㄉㄚˇ', cangjie: '手竹中弓', boshiamy: 'QHLN', pinyin: 'dǎ' },
    '字': { zhuyin: 'ㄗˋ', cangjie: '十弓木', boshiamy: 'JND', pinyin: 'zì' },
    '練': { zhuyin: 'ㄌㄧㄢˋ', cangjie: '女火火火木', boshiamy: 'VFFFD', pinyin: 'liàn' },
    '習': { zhuyin: 'ㄒㄧˊ', cangjie: '尸一卜', boshiamy: 'SMY', pinyin: 'xí' },
    '速': { zhuyin: 'ㄙㄨˋ', cangjie: '卜口束', boshiamy: 'YRDL', pinyin: 'sù' },
    '度': { zhuyin: 'ㄉㄨˋ', cangjie: '戈廿水', boshiamy: 'ITE', pinyin: 'dù' },
    '測': { zhuyin: 'ㄘㄜˋ', cangjie: '水月月金', boshiamy: 'EBBC', pinyin: 'cè' },
    '試': { zhuyin: 'ㄕˋ', cangjie: '卜口戈土', boshiamy: 'YRIG', pinyin: 'shì' },
    '開': { zhuyin: 'ㄎㄞ', cangjie: '日弓廿', boshiamy: 'ANT', pinyin: 'kāi' },
    '始': { zhuyin: 'ㄕˇ', cangjie: '女戈口', boshiamy: 'VIR', pinyin: 'shǐ' },
    '輸': { zhuyin: 'ㄕㄨ', cangjie: '十十人一月', boshiamy: 'JJOMB', pinyin: 'shū' },
    '入': { zhuyin: 'ㄖㄨˋ', cangjie: '人竹', boshiamy: 'OH', pinyin: 'rù' },
    '提': { zhuyin: 'ㄊㄧˊ', cangjie: '手日一人', boshiamy: 'QAMO', pinyin: 'tí' },
    '示': { zhuyin: 'ㄕˋ', cangjie: '一一火', boshiamy: 'MMF', pinyin: 'shì' },
    '按': { zhuyin: 'ㄢˋ', cangjie: '手十女', boshiamy: 'QJV', pinyin: 'àn' },
    '鍵': { zhuyin: 'ㄐㄧㄢˋ', cangjie: '金弓十手', boshiamy: 'CNJQ', pinyin: 'jiàn' },
    '查': { zhuyin: 'ㄔㄚˊ', cangjie: '木日一', boshiamy: 'DAM', pinyin: 'chá' },
    '詢': { zhuyin: 'ㄒㄩㄣˊ', cangjie: '卜口尸一一', boshiamy: 'YRSMM', pinyin: 'xún' },
    '編': { zhuyin: 'ㄅㄧㄢ', cangjie: '女火竹尸月', boshiamy: 'VFHSB', pinyin: 'biān' },
    '碼': { zhuyin: 'ㄇㄚˇ', cangjie: '一口尸手火', boshiamy: 'MRSQF', pinyin: 'mǎ' },
    '注': { zhuyin: 'ㄓㄨˋ', cangjie: '水卜土', boshiamy: 'EYG', pinyin: 'zhù' },
    '音': { zhuyin: 'ㄧㄣ', cangjie: '卜廿日', boshiamy: 'YTA', pinyin: 'yīn' },
    '倉': { zhuyin: 'ㄘㄤ', cangjie: '人戈口', boshiamy: 'OIR', pinyin: 'cāng' },
    '頡': { zhuyin: 'ㄐㄧㄝˊ', cangjie: '土口一月金', boshiamy: 'GRMBC', pinyin: 'jié' },
    '無': { zhuyin: 'ㄨˊ', cangjie: '大廿火', boshiamy: 'KTF', pinyin: 'wú' },
    '蝦': { zhuyin: 'ㄒㄧㄚ', cangjie: '中戈口竹水', boshiamy: 'LIRHE', pinyin: 'xiā' },
    '米': { zhuyin: 'ㄇㄧˇ', cangjie: '火木', boshiamy: 'FD', pinyin: 'mǐ' },
    '拼': { zhuyin: 'ㄆㄧㄣ', cangjie: '手中十竹', boshiamy: 'QLJH', pinyin: 'pīn' },

    // 更多常用字
    '把': { zhuyin: 'ㄅㄚˇ', cangjie: '手日山', boshiamy: 'QAU', pinyin: 'bǎ' },
    '給': { zhuyin: 'ㄍㄟˇ', cangjie: '女火人口', boshiamy: 'VFOR', pinyin: 'gěi' },
    '等': { zhuyin: 'ㄉㄥˇ', cangjie: '竹土日戈', boshiamy: 'HGAI', pinyin: 'děng' },
    '很': { zhuyin: 'ㄏㄣˇ', cangjie: '竹人日女', boshiamy: 'HOAV', pinyin: 'hěn' },
    '意': { zhuyin: 'ㄧˋ', cangjie: '卜廿日心', boshiamy: 'YTAP', pinyin: 'yì' },
    '明': { zhuyin: 'ㄇㄧㄥˊ', cangjie: '日月', boshiamy: 'AB', pinyin: 'míng' },
    '什': { zhuyin: 'ㄕㄜˊ', cangjie: '人十', boshiamy: 'OJ', pinyin: 'shé' },
    '知': { zhuyin: 'ㄓ', cangjie: '人口', boshiamy: 'OR', pinyin: 'zhī' },
    '最': { zhuyin: 'ㄗㄨㄟˋ', cangjie: '日日廿', boshiamy: 'AAT', pinyin: 'zuì' },
    '長': { zhuyin: 'ㄔㄤˊ', cangjie: '尸一女', boshiamy: 'SMV', pinyin: 'cháng' },
    '文': { zhuyin: 'ㄨㄣˊ', cangjie: '卜大', boshiamy: 'YK', pinyin: 'wén' },
    '正': { zhuyin: 'ㄓㄥˋ', cangjie: '一卜一一', boshiamy: 'MYMM', pinyin: 'zhèng' },
    '確': { zhuyin: 'ㄑㄩㄝˋ', cangjie: '一口人月山', boshiamy: 'MROBU', pinyin: 'què' },
    '每': { zhuyin: 'ㄇㄟˇ', cangjie: '人田卜', boshiamy: 'OWY', pinyin: 'měi' },
    '日': { zhuyin: 'ㄖˋ', cangjie: '日', boshiamy: 'A', pinyin: 'rì' },
    '更': { zhuyin: 'ㄍㄥˋ', cangjie: '一中田水', boshiamy: 'MLWE', pinyin: 'gèng' },
    '快': { zhuyin: 'ㄎㄨㄞˋ', cangjie: '心大大', boshiamy: 'PKK', pinyin: 'kuài' },
    '準': { zhuyin: 'ㄓㄨㄣˇ', cangjie: '水人土戈', boshiamy: 'EOGI', pinyin: 'zhǔn' },
    '讓': { zhuyin: 'ㄖㄤˋ', cangjie: '卜口卜口女', boshiamy: 'YRYRV', pinyin: 'ràng' },
    '加': { zhuyin: 'ㄐㄧㄚ', cangjie: '大尸口', boshiamy: 'KSR', pinyin: 'jiā' },
    '油': { zhuyin: 'ㄧㄡˊ', cangjie: '水竹中月', boshiamy: 'EHLB', pinyin: 'yóu' },
    '努': { zhuyin: 'ㄋㄨˇ', cangjie: '女大尸', boshiamy: 'VKS', pinyin: 'nǔ' },
    '力': { zhuyin: 'ㄌㄧˋ', cangjie: '大尸', boshiamy: 'KS', pinyin: 'lì' },
    '常': { zhuyin: 'ㄔㄤˊ', cangjie: '火月口', boshiamy: 'FBR', pinyin: 'cháng' },
    '高': { zhuyin: 'ㄍㄠ', cangjie: '卜口月口', boshiamy: 'YRBR', pinyin: 'gāo' },
    '新': { zhuyin: 'ㄒㄧㄣ', cangjie: '卜木竹中中', boshiamy: 'YDHLL', pinyin: 'xīn' },
    '老': { zhuyin: 'ㄌㄠˇ', cangjie: '十大心', boshiamy: 'JKP', pinyin: 'lǎo' },
    '師': { zhuyin: 'ㄕ', cangjie: '竹口一中月', boshiamy: 'HRMLB', pinyin: 'shī' },
    '認': { zhuyin: 'ㄖㄣˋ', cangjie: '卜口心心', boshiamy: 'YRPP', pinyin: 'rèn' },
    '真': { zhuyin: 'ㄓㄣ', cangjie: '十月一金', boshiamy: 'JBMC', pinyin: 'zhēn' },
    '話': { zhuyin: 'ㄏㄨㄚˋ', cangjie: '卜口竹十中', boshiamy: 'YRHJL', pinyin: 'huà' },
    '先': { zhuyin: 'ㄒㄧㄢ', cangjie: '竹木山', boshiamy: 'HDU', pinyin: 'xiān' },
    '全': { zhuyin: 'ㄑㄩㄢˊ', cangjie: '人一土', boshiamy: 'OMG', pinyin: 'quán' },
    '兩': { zhuyin: 'ㄌㄧㄤˇ', cangjie: '一中月金金', boshiamy: 'MLBCC', pinyin: 'liǎng' },
    '再': { zhuyin: 'ㄗㄞˋ', cangjie: '一土火山', boshiamy: 'MGFU', pinyin: 'zài' },
    '書': { zhuyin: 'ㄕㄨ', cangjie: '中土日', boshiamy: 'LGA', pinyin: 'shū' },
    '問': { zhuyin: 'ㄨㄣˋ', cangjie: '日弓口', boshiamy: 'ANR', pinyin: 'wèn' },
    '題': { zhuyin: 'ㄊㄧˊ', cangjie: '日一月金', boshiamy: 'AMBC', pinyin: 'tí' },
    '答': { zhuyin: 'ㄉㄚˊ', cangjie: '竹人一口', boshiamy: 'HOMR', pinyin: 'dá' },
    '工': { zhuyin: 'ㄍㄨㄥ', cangjie: '一', boshiamy: 'M', pinyin: 'gōng' },
    '重': { zhuyin: 'ㄓㄨㄥˋ', cangjie: '竹十土', boshiamy: 'HJG', pinyin: 'zhòng' },
    '三': { zhuyin: 'ㄙㄢ', cangjie: '一一一', boshiamy: 'MMM', pinyin: 'sān' },
    '手': { zhuyin: 'ㄕㄡˇ', cangjie: '手', boshiamy: 'Q', pinyin: 'shǒu' },
    '次': { zhuyin: 'ㄘˋ', cangjie: '戈一弓人', boshiamy: 'IMNO', pinyin: 'cì' },
    '已': { zhuyin: 'ㄧˇ', cangjie: '尸山', boshiamy: 'SU', pinyin: 'yǐ' },
    '點': { zhuyin: 'ㄉㄧㄢˇ', cangjie: '卜口月金火', boshiamy: 'YRBCF', pinyin: 'diǎn' },
    '見': { zhuyin: 'ㄐㄧㄢˋ', cangjie: '月山山', boshiamy: 'BUU', pinyin: 'jiàn' },
    '兒': { zhuyin: 'ㄦˊ', cangjie: '竹山山', boshiamy: 'HUU', pinyin: 'ér' },
    '情': { zhuyin: 'ㄑㄧㄥˊ', cangjie: '心手月一', boshiamy: 'PQBM', pinyin: 'qíng' },
    '比': { zhuyin: 'ㄅㄧˇ', cangjie: '心心', boshiamy: 'PP', pinyin: 'bǐ' },
    '較': { zhuyin: 'ㄐㄧㄠˋ', cangjie: '十十卜金大', boshiamy: 'JJYCK', pinyin: 'jiào' },
    '第': { zhuyin: 'ㄉㄧˋ', cangjie: '竹弓中月', boshiamy: 'HNLB', pinyin: 'dì' },
    '位': { zhuyin: 'ㄨㄟˋ', cangjie: '人卜廿', boshiamy: 'OYT', pinyin: 'wèi' },
    '目': { zhuyin: 'ㄇㄨˋ', cangjie: '月山', boshiamy: 'BU', pinyin: 'mù' },
    '十': { zhuyin: 'ㄕˊ', cangjie: '十', boshiamy: 'J', pinyin: 'shí' },
    '公': { zhuyin: 'ㄍㄨㄥ', cangjie: '金戈', boshiamy: 'CI', pinyin: 'gōng' },
    '民': { zhuyin: 'ㄇㄧㄣˊ', cangjie: '口女心', boshiamy: 'RVP', pinyin: 'mín' },
    '幾': { zhuyin: 'ㄐㄧˇ', cangjie: '女戈竹大', boshiamy: 'VIHK', pinyin: 'jǐ' },
    '件': { zhuyin: 'ㄐㄧㄢˋ', cangjie: '人竹手', boshiamy: 'OHQ', pinyin: 'jiàn' },
    '或': { zhuyin: 'ㄏㄨㄛˋ', cangjie: '戈口一弓', boshiamy: 'IRMN', pinyin: 'huò' },
    '數': { zhuyin: 'ㄕㄨˋ', cangjie: '中女人大', boshiamy: 'LVOK', pinyin: 'shù' },
    '表': { zhuyin: 'ㄅㄧㄠˇ', cangjie: '手一女', boshiamy: 'QMV', pinyin: 'biǎo' },
    '原': { zhuyin: 'ㄩㄢˊ', cangjie: '一竹日火', boshiamy: 'MHAF', pinyin: 'yuán' },
    '名': { zhuyin: 'ㄇㄧㄥˊ', cangjie: '弓戈口', boshiamy: 'NIR', pinyin: 'míng' },
    '應': { zhuyin: 'ㄧㄥ', cangjie: '戈土心', boshiamy: 'IGP', pinyin: 'yīng' },
    '者': { zhuyin: 'ㄓㄜˇ', cangjie: '十大日', boshiamy: 'JKA', pinyin: 'zhě' },
    '外': { zhuyin: 'ㄨㄞˋ', cangjie: '弓戈卜', boshiamy: 'NIY', pinyin: 'wài' },
    '間': { zhuyin: 'ㄐㄧㄢ', cangjie: '日弓日', boshiamy: 'ANA', pinyin: 'jiān' },
    '社': { zhuyin: 'ㄕㄜˋ', cangjie: '戈火土', boshiamy: 'IFG', pinyin: 'shè' },
    '體': { zhuyin: 'ㄊㄧˇ', cangjie: '月月廿金', boshiamy: 'BBTC', pinyin: 'tǐ' },
    '接': { zhuyin: 'ㄐㄧㄝ', cangjie: '手卜女水', boshiamy: 'QYVE', pinyin: 'jiē' },
    '決': { zhuyin: 'ㄐㄩㄝˊ', cangjie: '水大大', boshiamy: 'EKK', pinyin: 'jué' },
    '活': { zhuyin: 'ㄏㄨㄛˊ', cangjie: '水竹十口', boshiamy: 'EHJR', pinyin: 'huó' },
    '記': { zhuyin: 'ㄐㄧˋ', cangjie: '卜口尸山', boshiamy: 'YRSU', pinyin: 'jì' },
    '手': { zhuyin: 'ㄕㄡˇ', cangjie: '手', boshiamy: 'Q', pinyin: 'shǒu' },
};

// 取得字元編碼
function getEncoding(char) {
    if (encodingData[char]) {
        return encodingData[char];
    }
    return null;
}

// 檢查是否為中文字元
function isChinese(char) {
    return /[\u4e00-\u9fff]/.test(char);
}
